spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresher_manager
    username: thephung
    password: 123456

    data=myscript:
      sql:jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
        globally_quoted_identifiers: true
  sql:
    init:
      platform: oracle
server:
  port: 8080
  servlet:
    context-path: /fm
